### ISSUE TITLE
Adding a show is annoying

### ISSUE THREAD

**Issue by lethargilistic** [whiletruefm/whiletruefm.github.io#10]
So, the workflow for adding a new show, after it's been edited and prepared is:

1) Write shownotes in markdown
2) Convert Markdown to HTML (fix converter issues)
3) Copy the common information from an older episode (top, contact info)
4) Choose the title and description
5) Copy information to the podcast RSS
6) Update the index.html with the new episode

There a few pain points here that could probably be their own issues. But, generally, a lot of them exist because we're using a static site.

For example, writing HTML by hand isn't going to happen for shownotes, even if we don't go into the detail that I feel like going to. If we could put the markdown here directly, we could cut out the finicky conversion step.

We have to write the RSS by hand, which leaves us vulnerable to copy/paste problems.

If we forget to update the index.html, the new episode won't appear for users. We're using strong and br tags to separate the episodes, which is finicky as well.

We don't currently have a template for a new episode, so going back to the old episode involves a lot of copy/paste that could lead to problems.

**Comment by kennethlove** [comment]
So, static site generator? Wouldn't be that hard to stand our current design up in [Hugo](https://gohugo.io) and it's a button-click to get that hosted on Netlify. I can try and do this over the next week or two. Then publishing is a `git push` away and Hugo will handle the Markdown conversion and RSS feeds for us.

**Comment by kennethlove** [comment]
Is this better now that we're using Hugo?

**Comment by lethargilistic** [comment]
Yes, much better process. Nice job, Kenneth. ^^
