### ISSUE TITLE
Episode page is missing!!

### ISSUE THREAD

**Issue by thatweirdcoder** [whiletruefm/whiletruefm.github.io#11]
The page where the player and the notes are is not there. It only shows the title of the podcast! https://whiletrue.fm/2017/11/polite-and-inviting-to-amazon-key-and-sex-toys/

**Comment by thatweirdcoder** [comment]
I tried to help identify the problem but I think the code in the master branch is not the code of the online website. the links are different: in the master branch it links to './episode/0003.html', but in the live website it links to './2017/11/[episodeName]'.

**Comment by kennethlove** [comment]
Fixed. Thanks for telling us about it
